### ISSUE TITLE
Tests don't pass on edn-rs 0.17.4

### ISSUE THREAD

**Issue by Grinkers** [edn-rs/edn-derive#32]
`edn-rs = "0.17.4"`
I'm not familiar, yet, with `syn` or `proc-macro2`. I would rather get edn-rs to 1.0 stability (or at least a candidate) before messing with derive.

**Comment by naomijub** [comment]
@evaporei is a derive master, ask her if you need any help

**Comment by evaporei** [comment]
I think I can try out the new `edn-rs` this week and see if it's a simple fix. :slightly_smiling_face:

**Comment by evaporei** [comment]
btw @naomijub can you switch the main branch from `master` to `main`? or give me access to do it.

**Comment by evaporei** [comment]
Oh, I found out the issue, it starts on `0.17.0` (`0.16.14` works). It's because [this commit](https://github.com/edn-rs/edn-rs/commit/a9fce81a17cb9b3f3a618f4aa6376ee9e69e93d8#diff-29bbe7e773e060620976fc1ec77d4839e39a269170c619b0003929da05bd2d66L415) removed the implementation for `Serialize`. It should've only removed the `ser_struct` macro.

I can make a PR for it and test it.

**Comment by Grinkers** [comment]
> Oh I found out the issue, I'm making a fix. Quick question, I'm looking through the PRs and issues in `edn-rs`, but I can't find the discussion about this. We don't support the following anymore, right?
> 
> ```clojure
> :person{ 0 \"joana\", 1 290000, 2 :kind/pirate, }
> ```
> 
> The `:person{ ... }` part.


The discussion got scattered a bit because of so PRs getting out of scope and being broken up. That's not valid EDN so it was removed in

**Comment by naomijub** [comment]
> Oh I found out the issue, I'm making a fix. Quick question, I'm looking through the PRs and issues in `edn-rs`, but I can't find the discussion about this. We don't support the following anymore, right?
> 
> ```clojure
> :person{ 0 \"joana\", 1 290000, 2 :kind/pirate, }
> ```
> 
> The `:person{ ... }` part.

We do not support it as it is a clojure specific thing.
